ansible_host: "{{ mgmt_ip | ipaddr('address') }}"
interfaces:
  - interface: Gi0/4
    description: to lab-pe-3
    ip: 10.0.19.2/30
  - interface: Gi0/3
    description: to lab-p-1
    ip: 10.0.15.2/30
  - interface: Gi0/2
    description: to lab-pe-1
    ip: 10.0.13.2/30
  - interface: Gi0/1
    description: to lab-pe-2
    ip: 10.0.12.2/30
  - interface: Gi0/5
    description: to lab-pe-4
    ip: 10.0.17.1/30
  - interface: loopback0
    description: loopback0
    ip: 11.11.11.4/32
